sudo: false
language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install pytest pytest-cov flake8
script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  - py.test --cov=coverage --short tests
after_success:
  - coveralls
notifications:
  email:
    on_success: change
    on_failure: change
